### ISSUE TITLE
Coffescript error

### ISSUE THREAD

**Issue by lbarman** [christophetd/downbot#3]
I get the following error:

```
{ id: MYID,
  first_name: 'MYNAME',
  username: 'MYBOT' }
Checking http://MYURL

/PATH/telegram-downbot/worker.coffee:73
ck.bind(this, index).on('error', this.unreachable.bind(this, index).setTimeout
                                                                    ^
TypeError: Object function () { [native code] } has no method 'setTimeout'
    at Worker.checkOne (/home/stduser/telegram-downbot/worker.coffee:73:132)
    at null.<anonymous> (/home/stduser/telegram-downbot/worker.coffee:3:61)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

In the file:
`worker.coffee:79`

... this is the concerned snippet:

```
    @urls[index].checking = true
    http.get @urls[index].url, @responseCallback.bind(this, index)
      .on 'error', @unreachable.bind(this, index)
      .setTimeout 1000 * config.checkTimeout, @unreachable.bind(this, index, timeoutErrorString)
```

I use nodejs version `0.10.25`, installed with `npm 1.3.10` on a fresh `Ubuntu 16.10` install:

`$ npm version`

```
{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.10.0',
  uv: '0.10.23',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1f',
  npm: '1.3.10',
  downbot: '0.0.1' }
```

**Comment by lbarman** [comment]
it seems to be a parenthesis problem. I got it working by changing `worker.coffee`

```
    @urls[index].checking = true
    http.get @urls[index].url, @responseCallback.bind(this, index)
      .on 'error', @unreachable.bind(this, index)
      .setTimeout 1000 * config.checkTimeout, @unreachable.bind(this, index, timeoutErrorString)

  responseCallback: (index, res) ->
```

to

```
    @urls[index].checking = true
    request = http.get(@urls[index].url, @responseCallback.bind(this, index)).on('error', @unreachable.bind(this, index))
    request.setTimeout 1000 * config.checkTimeout, @unreachable.bind(this, index, timeoutErrorString)
    request

  responseCallback: (index, res) ->
```

**Comment by christophetd** [comment]
Thank you for catching this, @lbarman. PR appreciated
